# Generated by Django 4.2.7 on 2023-12-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł wpisu')),
                ('post', models.TextField(verbose_name='Treś wpisu')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data powstania wpisu')),
                ('edited', models.DateTimeField(null=True, verbose_name='Data aktualizacji wpisu')),
                ('slug', models.SlugField(max_length=255)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Kategoria zdjęcia')),
            ],
        ),
        migrations.CreateModel(
            name='FotoDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Opis zdjęcia')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Autor zdjęcia')),
                ('ivent', models.CharField(max_length=255, verbose_name='Z jakiego wydarzenia jest to zdjęcie')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data powstania opisu')),
                ('edited', models.DateTimeField(null=True, verbose_name='Data aktualizacji')),
                ('foto_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brashfox_app.fotocategory')),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Nazwa komentującego')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data powstania komnentarza')),
                ('edited', models.DateTimeField(null=True, verbose_name='Data aktualizacji edycji')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brashfox_app.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Kategoria wpisu na blogu')),
                ('blog_post', models.ManyToManyField(to='brashfox_app.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='FotoTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=60, verbose_name='Tag zdjęcia')),
                ('foto_description', models.ManyToManyField(to='brashfox_app.fotodescription')),
            ],
        ),
    ]
