# Generated by Django 5.1.5 on 2025-11-04 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brashfox_app', '0009_postcomments_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created'], 'verbose_name': 'Post blogowy', 'verbose_name_plural': 'Posty blogowe'},
        ),
        migrations.AlterModelOptions(
            name='fotocategory',
            options={'ordering': ['category'], 'verbose_name': 'Kategoria zdjęcia', 'verbose_name_plural': 'Kategorie zdjęć'},
        ),
        migrations.AlterModelOptions(
            name='fotodescription',
            options={'ordering': ['-created'], 'verbose_name': 'Opis zdjęcia', 'verbose_name_plural': 'Opisy zdjęć'},
        ),
        migrations.AlterModelOptions(
            name='fototags',
            options={'ordering': ['tags'], 'verbose_name': 'Tag zdjęcia', 'verbose_name_plural': 'Tagi zdjęć'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'Wiadomość', 'verbose_name_plural': 'Wiadomości'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['category'], 'verbose_name': 'Kategoria posta', 'verbose_name_plural': 'Kategorie postów'},
        ),
        migrations.AlterModelOptions(
            name='postcomments',
            options={'ordering': ['created'], 'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.RemoveField(
            model_name='fotodescription',
            name='ivent',
        ),
        migrations.AddField(
            model_name='fotodescription',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Z jakiego wydarzenia jest to zdjęcie'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=models.TextField(verbose_name='Treść wpisu'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='fotodescription',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor zdjęcia'),
        ),
        migrations.AlterField(
            model_name='fotodescription',
            name='foto_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='brashfox_app.fotocategory', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='fotodescription',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='fototags',
            name='foto_description',
            field=models.ManyToManyField(related_name='tags', to='brashfox_app.fotodescription', verbose_name='Zdjęcia'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='blog_post',
            field=models.ManyToManyField(related_name='categories', to='brashfox_app.blogpost', verbose_name='Posty'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='brashfox_app.blogpost', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='comment',
            field=models.TextField(verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data powstania komentarza'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='brashfox_ap_slug_e1f664_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-created'], name='brashfox_ap_created_77ed38_idx'),
        ),
    ]
