# Generated by Django 5.1.5 on 2025-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brashfox_app', '0010_improve_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='O mnie', help_text='Page title', max_length=200, verbose_name='Tytuł strony')),
                ('name', models.CharField(help_text='Artist name or pseudonym', max_length=100, verbose_name='Imię/Pseudonim')),
                ('bio', models.TextField(help_text='Biography/description (supports line breaks)', verbose_name='Biografia')),
                ('profile_image', models.ImageField(help_text='Profile photo (recommended: 800x800px, max 5MB)', upload_to='about/', verbose_name='Zdjęcie profilowe')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of specializations', verbose_name='Specjalizacje')),
                ('email', models.EmailField(blank=True, help_text='Contact email (optional)', max_length=254, null=True, verbose_name='Email kontaktowy')),
                ('phone', models.CharField(blank=True, help_text='Contact phone (optional)', max_length=20, null=True, verbose_name='Telefon kontaktowy')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text="Social media links (e.g., {'instagram': 'url', 'facebook': 'url'})", verbose_name='Linki do mediów społecznościowych')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'O mnie',
                'verbose_name_plural': 'O mnie',
            },
        ),
    ]
