# Generated by Django 4.2.7 on 2023-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brashfox_app', '0004_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotodescription',
            name='image',
            field=models.ImageField(default=None, upload_to='./static/images/portfolio'),
            preserve_default=False,
        ),
    ]
