# Generated by Django 4.2.7 on 2023-12-12 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brashfox_app', '0005_fotodescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotodescription',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data aktualizacji'),
        ),
    ]
