# Generated by Django 4.2.7 on 2023-12-15 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brashfox_app', '0008_alter_blogpost_created_alter_blogpost_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='comment',
            field=models.TextField(default=datetime.datetime.now, verbose_name='Komentarza'),
            preserve_default=False,
        ),
    ]
